theme = "detox"
baseURL = "https://asonty.github.io/"
languageCode = "en-us"
title = "H₁ "
publishDir = "asonty.github.io"

customCSS = ["/css/main.css"]
customCSSP = ["/css/obsidian.css"]

[params]
    intro = true
    headline = "adam sonty"
    description = "[ data | sports | ··· ]"
    github = "/asonty"
    linkedin = "https://linkedin.com/in/asonty"
    email = "sonty1@umbc.edu"
    #summary_length = 20
    